version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cienciastop_db
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: amazoncorretto:11-alpine
    working_dir: /home/app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run
    depends_on:
      - db
    volumes:
      - .:/home/app
      - mvn_data:/root/.m2

volumes:
  mvn_data:
  db_data:
